### ISSUE TITLE
Feature request: save_data() run periodically

### ISSUE THREAD

**Issue by ewildgoose** [mobius-home/mobius#38]
Hi, I really like the look of what you have here! (I found this project through your video at ElixirConf) However, I have a use case for it on an IOT device where there is no off button... Customers just pull the power when they are finished. So I'm looking to make it halfway useable in such a situation. 

I guess a minimal option would be to write a timer which pings the existing save function periodically, however, it isn't technically exposed through your top level public API. However, I wonder if you would consider adding a simple timer genserver inside the project to simplify inclusion, perhaps something passed via childspec which just kicks off a periodic call to save?

For my use case I would be targeting a period in the 1-5 min range. Seems short enough to not lose too much data, but not enough to blow my SD card life too quickly. 

Is a neater option possible? Cubdb (and sqlite) seem robust against partial writes? Can we perhaps sync the data dump with periodic updates of the data, ie match the time frames? Other possibilities?

Thanks for this super library!

**Comment by mattludwigs** [comment]
Hey, @ewildgoose thank you for your suggestion - I really like it - and your kind words.

I have some work in Mobius to wrap up later this week or next week and I can get to implementing this then. However, feel free to make a PR as well in the meantime if you want.

I am thinking that when Mobius [initializes](https://github.com/mattludwigs/mobius/blob/main/lib/mobius.ex#L49) we can check if the save interval is set. If so, we add the child spec for the GenServer to Mobius' children list, otherwise, we don't add the child spec.
